### ISSUE TITLE
Problems viewing in IOS

### ISSUE THREAD

**Issue by arikanev** [BlackrockDigital/startbootstrap-bare#15]
Here's my code:

     `{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ari Kanevsky - Welcome</title>
    <title style = "display:none">Akanev akanev AKANEV</title>

    

    <link href= "{% static 'ari/index/node_modules/startbootstrap-bare/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    
    <style>
      body {
        padding-top: 54px;
        background-color:grey;
      }
      @media (min-width: 992px) {
        body {
          padding-top: 56px;
        }
      }

    </style>

  </head>

  <body>

    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-  target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="">home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="1/support">support</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="1/bio">bio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="1/experience">experience</a>
            </li>
            <h1 class="mt-5" style="color:white">Ari Kanevsky</h1> 
            <li class="nav-item">
              <a class="nav-link" href="1/projects">projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="1/publications">publications</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="1/education">education</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/datasets">datasets</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <p class="lead"></p>
          <ul class="list-unstyled">
          </ul>
        </div>
      </div>
    </div>

    
    <script src="{% static 'ari/index/node_modules/startbootstrap-bare/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ari/index/node_modules/startbootstrap-bare/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>`

What I am doing wrong? Displays fine in desktop browsers, not in mobile.

Thanks

**Comment by davidtmiller** [comment]
Your viewport tag looks fine, do you have a screenshot of what's going on with mobile?

**Comment by arikanev** [comment]
I ended up implementing a css theme from scratch, I don't have any screenshot's from the mobile display with the startbootstrap-bare theme. Sorry- I'll close this issue since I can't verify or deny any potential fixes.
